version: '3.1'
services:
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      MYSQL_DATABASE: tcc_db
    ports:
      - 5432:5432
    volumes:
      - $HOME/database/pg:/var/lib/postgresql/data
